## Programming for Data Analysis - Assignment

This notebook is for the assignment for ProgDA - Author: Sheldon D'Souza (email: g00387857@gmit.ie)

***

#### Problem statement

The assignment concerns the numpy.random package in Python. You are required to create a Jupyter notebook explaining the use of the package, including detailed explanations of at least five of the distributions provided for in the package. There are four distinct tasks to be carried out in your Jupyter notebook.

1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.


Project Plan:
- Research the numpy.random package via official documentation and online tutorial videos.
- Research the Simple random data and Permutatin functions via official documentation and online tutorial videos.
- Choose 5 Distributions functions. Choose a dataset or generate data to show the differences between the distibution
- Research seeds generation and given coded example
- Research creative methods to "explain" the above narratively and/or visually  


<img src=https://live.staticflickr.com/748/20445410340_c1a0fe6a6a_b.jpg alt="Randomness" width="500"/>


*Image Credit: "Binary code" by Christiaan Colen is licensed under CC BY-SA 2.0*


##### Note - Important changes to numpy.random

There have been some changes to the numpy random module since version 1.17.0. These changes are summarised on the numpy wesite page below:

https://numpy.org/devdocs/reference/random/index.html

A very brief overview of the changes are as follows:

Numpy 1.17.0 introduces a new random number generator system. While the details of this (Bitgenerators and Generators) can be quite technical, simply put the older system made use of the global random generator object which was shared across the application. The newer system creates a random generator object with default_rng() and uses that object to generate random numbers without relying on the global state. The older system (RandomState) is not obsolete, rather, in most cases, it should be avoided whenever reproducible "randomness" is required.

The older system used the Mersenne Twister BitGenerator whereas the new system uses the the PCG65 Bitgenerator. As per numpy.org offical documentation(https://numpy.org/doc/stable/reference/random/index.html):

>Call default_rng to get a new instance of a Generator, then call its methods to obtain samples from different distributions. By default, Generator uses bits provided by PCG64 which has better statistical properties than the legacy MT19937 used in RandomState.

#### Part 1 - The purpose of the Numpy.random package

##### The problem with generating randomness

*What is a random number/sequence*

A numeric sequence is said to be statistically random when it contains no recognizable patterns or regularities; sequences such as the results of an ideal dice roll or the digits of π exhibit statistical randomness.[1]

*Why is it so difficult to generate a random number/sequence*

Computers need instruction or programs to generate to do any task which includes generating random numbers. This means that an algrothim will also needed to generate a random number. The fact that there is an algrothim behind the generation means that it is not completely random and therefore these numbers are called pseudo random numbers ("PRN").[2]

##### What does numpy.random do

As per official documentation:

> Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions [3]

In other words any pseudo random numbers generator such as numpy.random will use an alogrothim to produce a stream of numbers which would exhibit statistical randomness. A 'seed' is often used as a 'starting point which is 'fed' into a software algrothim to produce a sequence of seemingly random numbers. The seed used can either be specified or can be automatically selected by e.g. the current date/time of the system running the generator etc.[4]   


A very simple way of looking at this would be in the example below:

In [119]:
def random_gen(how_many_nos=10, seed=400): #demo limitation - max number of items is 20 and seed value between 400 and 800
    l = []
    for n in range((how_many_nos)):
        seed = (seed/7) + (n * 5) + ((2 * 3/50) % 4) + (22/7) # this is an example of a software algorithim number generator
        y = str(seed) #convert number to string for slicing
        z = y[4:8] #using slicing to further 'randomise numbers'
        l.append(int(z)) #convert back to integer

    print(l) #used instead of return() so that all values can be seen below

In [120]:
random_gen(5,560)
random_gen(4,442)
random_gen(8,650)
random_gen(5,560)

[6285, 5755, 4250, 6892, 127]
[571, 4938, 9848, 1978]
[2, 9428, 489, 641, 663, 666, 3523, 6789]
[6285, 5755, 4250, 6892, 127]


The above function would be an example of an algorithim based generator which based on the seed would generate a list of seemingly random numbers. The key here is to generate a sufficiently long sequence of numbers is and based on a 'seed' number, the result will have the effect of being randomly generated. 

In the function above the user will include the number of random items to be generated along with a seed number (to reproduce results. Both inputs are then incuded in a software equation to generate a random number. In the above example I have converted the resultant number to a text string and then taken a slice of that string, to further randomise the number.

As can be seen above, If the same seed is used, the same sequence of random numbers will be generated.

The above is a very crude example of explaining how a generator like numpy generates pseudo random numbers

References
[1] - https://en.wikipedia.org/wiki/Statistical_randomness

[2] - https://www.w3schools.com/python/numpy_random.asp

[3] - https://numpy.org/doc/stable/reference/random/index.html?highlight=random#what-s-new-or-different

[4] - https://realpython.com/python-random/

[5] - https://stackoverflow.com/questions/59728162/how-to-use-numpy-random-to-generate-random-numbers-from-a-certain-distribution



#### Part 2 - Use of 'Simple Random Data' and 'Permutations' functions

###### 'Simple Random Data' functions


A 'Simple Random Data' function within numpy is, as the name suggests, a function to generate a 'simple' randomly generated value or array of values. Here simple means that each number within the range, has an equal chance of being selected/generated at every iteration of selection. A a real word example if we are rolling a die, each number from 1 to 6 has an equal chance of being selected on each roll.

This is as opposed to data generated by a 'Distribution' which may have a certain 'weighting' towards certain values of range of values which may be expected to occur more frequently than others. An example of this is that if we are generating random values with regards to height of a population, we would expect the results to be skewed in way which would result in a greater number of values generated towards a 'mean' height.


There are a number functions inbuilt within numpy to generate 'simple' random data:

| Function | Description |
| :-------- | :----------- |
| integers | Return random integers from low to high |
| random | Return random floats in the half-open interval (0.0, 1.0) |
| choice |Generates a random sample from a given 1-D array |
| bytes | Return random bytes |


*Integer Function*

>Return random integers from low (inclusive) to high (exclusive), or if endpoint=True, low (inclusive) to high (inclusive). Replaces RandomState.randint (with endpoint=False) and RandomState.random_integers (with endpoint=True)
>
>Return random integers from the “discrete uniform” distribution of the specified dtype. If high is None (the default), then results are from 0 to low.

The 'Integer' function returns a random integer between a specified range of two numbers (low and high). By default the low value is included in the selection range and the high number is excluded from the selection range. See below: 

In [20]:
import numpy as np
np.random.default_rng().integers(2,10) #2 is the low and 100 is the high value

7

If the argument endpoint=True is passed than the high and the low values are included in the selection range of the function. As below:

In [21]:
np.random.default_rng().integers(2,10, endpoint=True) #2 is the low and 100 is the high value; endpoint=True

5

If the size argument is passed to the function the function will return an array of the dimensions specifed in the size argument. As below:

In [22]:
print('This is a example of a one dimentional array of randomly generated numbers within a specifed range:')
x = np.random.default_rng().integers(2,10, size=(2))
print(x)
print()
print('This is a example of a two dimentional array of randomly generated numbers within a specifed range:')
y = np.random.default_rng().integers(2,10, size=(2,4))
print(y)

This is a example of a one dimentional array of randomly generated numbers within a specifed range:
[4 6]

This is a example of a two dimentional array of randomly generated numbers within a specifed range:
[[7 5 6 2]
 [8 6 8 5]]


*random function*

>Return random floats in the half-open interval (0.0, 1.0).
>
>Results are from the “continuous uniform” distribution over the stated interval. To sample Unif(a, b), b > a multiply the output of random by (b-a) and add a:
>
> `(b - a) * random() + a`


The random funtion returns a random number between 0 and 1. Where 0 is included in the selection and 1 is excluded in the selection. The result of the function are 'continuous' random floating point numbers.  See below:  

In [24]:
np.random.default_rng().random()

0.13237455220166083

If the size argument is passed to the function, the function will return an array of the dimensions, specifed in the size argument. As below:

In [25]:
np.random.default_rng().random(size=(2,3))

array([[0.51940931, 0.50767173, 0.32331463],
       [0.09068127, 0.48579871, 0.96606078]])

If the user wants to sample between a range of numbers a & b, where a is the 'lower' value and b is the 'higher' value, then this can be done by using a 'formula' within the function:

`(b - a) * random() + a`

So in other words if we want to sample from values of 2 to 10 using the 'random' function the way to do this would be as follows:

In [31]:
print('The sample selected between the range 2 and 10, using the random function')

(10 - 2) * np.random.default_rng().random() + 2

The sample selected between the range 2 and 10, using the random function


6.979964305621499

*choice function*

> `Generator.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)`
>
>Generates a random sample from a given 1-D array

The `choice` function takes in as input an array and returns random value(s) from the input. The input is generally in the form of an array, however the choice function is flexible enough to take in a various types of number sequences as inputs incuding lists, tuples etc. The output is an array of  numeric values or a single value (if a 1D array is passes as an input). Simply put the function makes a random choice(s) from a given group/set/array of numbers provided and returns the chosen values.

The input can also be a multidimentional array, however this is not covered within the explanation here.

As can be see above the function has only one required argument 'a' which is the 'input'.


In [24]:
import numpy as np

x = np.random.default_rng().choice(15)
print('A single number as an input works like the range() function where numbers are generated upto but excluding the input digit')
print(x)

print()
y = np.random.default_rng().choice(([ 12,  18,  35]))

print('This is an example of an array as an input:')
print(y)

A single number as an input works like the range() function where numbers are generated upto but excluding the input digit
11

This is an example of an array as an input:
35


The size argument will allow the user of the function to specify the size (or dimensions) of the output array, constructed by randomly choosing from the input.

In [27]:
np.random.default_rng().choice(15, size=(1,3))

array([[ 1, 10,  2]], dtype=int64)

The replace argument can be set to True or False. This argument will determine whether the value the first value selected will be 'replaced' or included back into the population when the second choice is made. In other words the replace function will determine whether the number sampled will be removed from the population when the second (and subsequent) choices. When replace=False, each value from the population will only have a chance of being selected be selected once.

In [42]:
x = np.random.default_rng().choice(8, size=(1,8), replace=False)
print('Each value will be selected only once:')
print(np.sort(x)) #sorted for ease
print()

y = np.random.default_rng().choice(8, size=(1,8), replace=True)
print('Each value can be selected multiple times:')
print(np.sort(y))

Each value will be selected only once:
[[0 1 2 3 4 5 6 7]]

Each value can be selected multiple times:
[[0 1 1 3 3 3 5 7]]


The 'p' argument will specify the probability of each item of input being selected. If no value is given to p, the choice function gives each item an equal chance (or probability of being selected)

In [51]:
x = np.random.default_rng().choice((1,2,3,4,5,6), size=(1,8), replace=True, p=(0.01,0.01,0.01,0.01,0.48,0.48))
print('The results will be skewed towards the items with higher probability:')
print(np.sort(x))

The results will be skewed towards the items with higher probability:
[[4 5 5 5 5 5 6 6]]


*bytes function*

> `Generator.bytes(length)`
>
>Return random bytes.

The bytes function returns random bytes of the length specified within the function. Generating random bytes may be used for the purpose of testing, however as specified within the documentation, numpy random numbers are not cryptographically secure and therefore should not be used for this purpose.

In [4]:
import numpy as np
x = np.random.default_rng().bytes(10)
print(x)

b'\x176\x87\x03\x17|\x9d\x9a\xf9)'


As explained in the Real Python 'Generating Random Data in Python (Guide)', these random bytes are displayed as a mix between hexadecimal characters and literal printable characters:

>These backslashes are escape sequences, and \xhh represents the character with hex value hh. Some of the elements of bites are displayed literally (printable characters such as letters, numbers, and punctuation). Most are expressed with escapes.
>
>Reference: https://realpython.com/python-random/


The bytes characters generated can be converted into decimal, hexadecimal or binary characters as shown below:

In [33]:
print('As shown above this is the bytes string generated by the function:')
x = np.random.default_rng().bytes(10)
print(x)
print()

print('This is the hexadecimal equivalent of the bytes generated:')
print(x.hex())
print()


print('This is a  list of the decimal value of each byte generated:')
y = list(x)
print(y)
print()

print('This is a list of the hexadecimal value of each byte generated:')
print([hex(a) for a in y])
print()

print('This is a list of the binary value of each byte generated:')
print([bin(a) for a in y])


As shown above this is the bytes string generated by the function:
b'\xe5\xaaHe\x91\xa9\xf64\xe2\x1a'

This is the hexadecimal equivalent of the bytes generated:
e5aa486591a9f634e21a

This is a  list of the decimal value of each byte generated:
[229, 170, 72, 101, 145, 169, 246, 52, 226, 26]

This is a list of the hexadecimal value of each byte generated:
['0xe5', '0xaa', '0x48', '0x65', '0x91', '0xa9', '0xf6', '0x34', '0xe2', '0x1a']

This is a list of the binary value of each byte generated:
['0b11100101', '0b10101010', '0b1001000', '0b1100101', '0b10010001', '0b10101001', '0b11110110', '0b110100', '0b11100010', '0b11010']
